# Generated by Django 3.2 on 2021-07-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_alter_orderitem_oreder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='oreder',
            new_name='order',
        ),
    ]
